version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "${GF_PORT:-3000}:3000"
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      PROMETHEUS_URL: "http://prometheus:${PROMETHEUS_PORT:-9090}"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml.tmpl:/etc/prometheus/prometheus.yml.tmpl
      - ./prometheus/entrypoint.sh:/entrypoint.sh
    environment:
      PROMETHEUS_TARGET: ${PROMETHEUS_TARGET:-localhost:9090}
      WALRUS_NODE_TARGET: ${WALRUS_NODE_TARGET:-localhost:9184}
      WALRUS_AGGREGATOR_TARGET: ${WALRUS_AGGREGATOR_TARGET:-localhost:27182}
      WALRUS_PUBLISHER_TARGET: ${WALRUS_PUBLISHER_TARGET:-localhost:27183}
    entrypoint: ["/entrypoint.sh"]

volumes:
  grafana_data:
    driver: local
  prometheus_data:
    driver: local
